### ISSUE TITLE
Error during saving deck file

### ISSUE THREAD

**Issue by wzajchow** [guicaulada/exams2anki#2]
Hi,
every time I try to generate deck for AWS Solutions Architect I'm getting an error: `OSError: [Errno 22] Invalid argument: 'ExamTopics::Amazon::Aws Certified Solutions Architect Associate Saa C03.apkg'`

![image](https://user-images.githubusercontent.com/83283986/220640686-3a94b0d1-692b-4e2e-81ba-03533317f316.png)

**Comment by wzajchow** [comment]
Okay, it's Windows related issue. ':' is not allowed in filename in Windows.

**Comment by guicaulada** [comment]
I believe this problem might have been related directly to `genanki` and updating the dependency fixed it.
